### PR TITLE
Updates + Comments 

### PR DESCRIPTION
**Pull request by Planeshifter**
Thanks again for your contribution!

Did you use the yeoman generator to set up the module? It's outdated, unfortunately, sorry about that. Will be updated shortly. I have updated the dotfiles and switched from `coveralls` to `codecov`, as the former code coverage service had frequent outages in the past. With `codecov`, if you happen to use Chrome, there is also a nice plugin to directly view the coverage reports on Github in the Browser. You might want to check that one out.

I made some other slight changes with respect to the code style, and added comments to outline our current thinking. Please share your thoughts and objections in case something sounds unreasonable to you. 

With respect to the Factory function, I removed it and simply exported the constructor function. The only rationale for the Factory function was that it would be invoked without the `new` keyword, correct? I changed the constructor function so that it can be also invoked without `new`, as this is how we have handled constructors in the past. Does this sound reasonable or are there reasons to revert this change?

Some other comments are directly attached to the relevant lines.

Please let me know any questions or comments you have.

### CODE REVIEW

**Comment by kgryte** [comment]
@Planeshifter I do not see this as being an issue. For most of the things we write, using `let` is not going to confer much advantage. And even if in some corner case the compiler could make the code run a wee bit faster if `let` was used instead of `var` that will inevitably be negligible compared to other operations.

Even if we did choose to drop `var` support, we could still do a find and replace, as `let` would simply declare the variables within the `function` scope, and thus be a drop-in replacement for `var`.

While I have been giving considerable thought to ES2015 and even using `babel`, the fact that a) `const` and `let` were not supported until [Node v0.12](https://strongloop.com/strongblog/es6-variable-declarations/) and that b) a majority of companies still run on either `v0.8` or `v0.10` (discussed at Node.js Interactive), I would currently contend that such a change will not happen anytime soon.

**Comment by kgryte** [comment]
Also, I am not seeing why this module should export a class constructor. I see two use cases: 1) integrate for `x` number of times and 2) incremental integration allowing each step to inspected, which might be useful for, say, visualization.

In which case, I would probably want those two use cases be separate autonomous `functions`.  The former case can then simply take an `options` object with an option `n`, for the number of iterations. The latter case can use partial application, similar to `incrmean` and the like.

We will need to clean the tests such that we do the usual gamut of various arg types. 

The model current accepts `array-like` inputs. What about `accessors` or `deep-set`? For `matrices`, would we do across a dimension?

I wonder if the `function` signature should be

``` javascript
function integrate( fcn, init[, opts] ) {
  // ...
}
```

with sensible defaults for `t` and `dt`.

**Comment by rreusser** [comment]
Thanks for the feedback! This module is trivial enough not to trigger most of the complexities, but I was aiming for swappability with more interesting methods that have these features:
1. Euler requires a derivative **storage vector**, and higher order methods require (potentially many) **work vectors** as well. See: [RK4](https://github.com/scijs/ode-rk4/blob/master/lib/index.js#L14-L20). (The constructor trick needs to vanish, but that's a separate issue.) It seemed best to me to encapsulate this and avoid long fortran-style argument lists, though maybe encapsulating allocation and state should be the job of a convenience wrapper.
2. For adaptive methods, **`dt` is a state, not a parameter**. See: [RK45-CK](https://github.com/scijs/ode45-cash-karp/blob/master/lib/index.js#L269). Adaptive integration has a different set of priorities, so I was aiming for as similar as possible an API that exposes what's interesting and hides (without fully obscuring) the internals.
3. Implicit methods may require **matrix operations**. (The basic idea is that you use iteration to converge on the derivative at a timestep you haven't yet reached. See: [Implicit RK methods](https://en.wikipedia.org/wiki/List_of_Runge%E2%80%93Kutta_methods#Implicit_methods). I believe diagonally-implicit methods may not actually require matrices, but there's no shortage of numerical methods that will accept vectors and need to deal with matrices). The thought of internally wrapping inputs in ndarrays/matrices/similar again made me think internal state was necessary.

My initial approach was to return a state object that could be re-passed to iteration functions, but I felt like I was mostly just avoiding `new` on principle alone.

As you've pointed out, the data type issue looms large. I'd love to figure out an acceptably standardish convention for what sort of inputs and outputs these modules can be reasonably expected to work with, even if that means an integration routine won't simply accept `Array`s or `typed-arrays`. At risk of comparing to Python, you wouldn't dream of dealing in `list`s of numbers. It seems ridiculous to forbid them, but they do complicate. I don't know the right answer for JS.

A lightly-pathological example that was the source of me getting a little bent out of shape: I wrote this the other day: [kerr-metric-tensor](https://github.com/rreusser/kerr-metric-tensor). Breaking my code into reusable pieces meant I essentially had to unwrap and rewrap most pieces of data every time I passed them because I can't guarantee anything about how people will be thinking of data as a matrices and vectors.

So questions:
- If not a constructor, then a state object as input/output? Explicit argument lists with a convenience wrapper? Passing five work vectors to RK4 is something I'd like to avoid.
- Is it necessary to conform to the style of [sum](https://github.com/compute-io/sum), for example, and enumerate types? Is it in the realm of possibility to think about disallowing unwrapped types, à la numpy?
- Can you clarify or point to an example of testing "the usual gamut of various arg types"? (If this refers to typed array types, I had some trouble testing the accuracy of various integration methods because `Float32Array` vs. `Float64Array` is enough to change the accuracy of high order methods in a way that's fine and necessary but rather fragile to test. (e.g. verifying 8th order accuracy typically requires extended precision.))

Again, I appreciate the feedback. These are the not-exactly-enthralling technical issues that keep me up at night because, for lack of resolving them adequately, my code just ends up… more or less bad/unusable. I'd love to converge on some pragmatic solutions and get back to writing modules.

Thanks!

**Comment by rreusser** [comment]
(Of course Python lists don't necessarily enjoy the optimization JS arrays have seen, which was probably actually a boon to numpy.)

**Comment by kgryte** [comment]
A convenience wrapper seems reasonable. We provide something like that with `dstructs/matrix`, where the main export has a polymorphic interface, but the constructor is an extended argument list. We see two use cases here: the former for a REPL, the latter for application code. One of principal reasons for validating input arguments is for interactive environments. For application code having tests, etc, we like to expose lower level interfaces. Something similar could possibly be done here.

Re: `lists` and `arrays`. Numpy methods seem to typically accept `array-like` args, which means `lists` are accepted (e.g., [`sin`](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.sin.html#numpy.sin)).

In JS and input args, yeah, this is tricky. So much of what people currently do, especially in data visualization, involves vanilla `arrays` and JSON. D3, in particular, essentially codified the accessor pattern, thus allowing complex data structures to be leveraged for data viz **without** requiring intermediate data formats, etc.

Granted, life would be easier from a development perspective if we forced people to use particular data structures / interfaces. I could, however, see this as a deterrent for actually using the modules; e.g., why marshal and unmarshal when I can just write a `function` which operates on the data (in an `array`) directly?

Of course, it is worth pointing out that the reality is `matrices`, `ndarrays`, etc, are just vanilla `arrays` and `typed-arrays` with some API sugar. In which case, seems a bit odd that we would reject vanilla data sets and only accept the same data sets with a couple extra attributes, especially if those attributes are not required for `function` to work. For instance, `sin()`, `cos()`, etc, don't need to know a `matrix` shape when performing an element-wise operation.

For other operations, say, inverting a `matrix`, then, sure, requiring a `matrix` is understandable, as the extra meta-information is necessary. So, here, the question is whether the extra meta information is necessary for the module to work? My thinking is no.

Re: testing. The usual gamut refers to checking that validators work correctly. Meaning, if an argument must be an `array`, then we should test that a `string`, `number`, `boolean`, `null`, `undefined`, `{}`, `function(){}`, `NaN`, etc are not allowed through (i.e., the `function` should `throw`). The gamut is mainly used to test argument validation.

Re: `typed-arrays`. Does it make sense to only accept `float64` `arrays`? Or maybe we could accept all types of `typed-arrays`, but, internally, anything other than `float64` gets [cast](https://github.com/dstructs/cast-arrays) to `float64`? I might go for the latter.

Re: `matrices`. Accepting a `matrix` would mean accepting multiple initial states, not that `matrix` operations are necessarily involved. For example, each `matrix` row could be a set of initial parameters. The algorithm would then solve the ODE for each row. (ala axis based operations) Obviously, this could be complex in the general case where multiple input arguments are `matrices` and thus argument combinations are permitted (e.g., a collection of 10 initial states where each state is tested against a collection of 10 parameter sets; thus 100 different combinations). (**NOTE**: I am not necessarily advocating for this. More about who shoulders the complexity.)

Do we have any reference APIs for how these algos are implemented in other platforms? e.g., [scipy](http://docs.scipy.org/doc/scipy-0.14.0/reference/integrate.html).

**Comment by rreusser** [comment]
Working on rev 2. Will update. Will be away from computer for a couple weeks over Christmas, so might be a little slow.

Re: `scipy`: I haven't read their code (I should), but they mostly wrap legacy fortran code in objects. They have basically one `ode` interface with `method` as a parameter. I think multiple modules are more appropriate here, in particular since we're not just interfacing with legacy code, so testing and versioning individual methods is more relevant. `scipy` example:

``` python
r = ode(f, jac).set_integrator('zvode', method='bdf', with_jacobian=True)
r.set_initial_value(y0, t0).set_f_params(2.0).set_jac_params(2.0)
t1 = 10
dt = 1
while r.successful() and r.t < t1:
    r.integrate(r.t+dt)
    print("%g %g" % (r.t, r.y))
```

So an object with configuration setters. (Perhaps I should handle the complex case first instead of the trivial one.) Either way, I think an object is necessary to manage allocation, validations and state efficiently. So yes, maybe a verbose low-level function wrapped in an object. I left configuration accessible on the raw object, but maybe the interface should proxy that through tightly-controlled getters/setters that validate. If validating getters/setters aren't compatible enough, then maybe `set_dt` et al. This gets at a larger question of what sort of interface you want to create. Fully managed and ready to plug into the end user? _Everything_ validated?

Re: numpy: yes, I wasn't strictly correct. Was thinking of its tendency to gravitate toward numpy arrays, e.g.

``` python
>>> np.sin([1,2,3])
array([ 0.84147098,  0.90929743,  0.14112001])
```

which I take to be an application of the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) with subtext "yeah, anything goes for casual input, but let's stick with numpy." Perhaps the JS ecosystem is different since a single standard isn't so pervasive. I have an unpublished ndarray-cast module that makes anything within reason an ndarray so you could presumably accept liberally and output ndarrays, but the checks based on existing modules were mostly cascading string comparisons that aren't acceptable for general application.

Tangentially related: I've been thinking about Flow/TypeScript and Babel, wondering if some sort of static type checking and transpiling could be leveraged to optimize and allow a `c = a + b` --> `Matrix.add(c, a, b)` sort of transformation, but I think even the best-case scenario would be too much of a buy-in, e.g. [paperscript](http://paperjs.org/reference/paperscript/)—which is fine and great!—but way too much of a buy-in for general application.

Re: `typed-arrays`: I think the least surprising solution is to permit any sort of array with the expectation that if you're using UInt8 arrays for numerical integration your results will be a little weird. I don't see a good reason to blacklist or forcibly convert datatypes. It seems to me a testing inconvenience for an application that's otherwise valid if it's what you want.

**Comment by rreusser** [comment]
Not to miss the point via email about just a version with just a function and a closure, which I like, as long as it's not too byzantine to create an object and a closure form that tap into the same validation/config/etc.

**Pull request merged**
